Models/BasedeDatos.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Tablas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Telefonos> Telefonos { get; set; }
    }
}

Models/BasedeDatos.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\Benjamin\Documents\UTT\5toCuatrimestre\D.web\3Tablas\Models\BasedeDatos.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

Models/BasedeDatos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

Models/Direccion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Tablas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int Id { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public int Cp { get; set; }
        public string NumInterior { get; set; }
        public string NumExterior { get; set; }
        public int IdPersona { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}

Models/Personas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Tablas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personas()
        {
            this.Direccion = new HashSet<Direccion>();
            this.Telefonos = new HashSet<Telefonos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int Edad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefonos> Telefonos { get; set; }
    }
}

Models/Telefonos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Tablas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int Id { get; set; }
        public string NumeroCelular { get; set; }
        public string NumeroFijo { get; set; }
        public int IdPersona { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _3Tablas.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _3Tablas.Servicios;
using _3Tablas.ViewModel;

namespace _3Tablas.Controllers
{
    public class PersonaController : Controller
    {

        private readonly PersonasServicios servicios = null;

        public PersonaController()
        {
            servicios = new PersonasServicios();
        }
        

        // GET: Persona/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PersonasVM personasVM)
        {
            if (ModelState.IsValid)
            {
                servicios.GuardarPersonas(personasVM);
                return View();
            }
            return RedirectToAction("Error", "Error");
        }


       


    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Persona/Create.cshtml
@model _3Tablas.ViewModel.PersonasVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registro de Personas</h2>


<div class="container">

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="panel-title">
                        Captura de Datos personales
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        @using (Html.BeginForm("Create", "Persona", FormMethod.Post))
                        {
                            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                                <label>Nombre:</label>
                                @Html.TextBoxFor(model => model.Nombre, null, new { @class = "form-control", placeHolder = "Nombre", Required = "Required" })
                                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <label>Apellido Paterno:</label>
                                @Html.TextBoxFor(model => model.ApellidoPaterno, null, new {@class = "form-control", placeHolder = "Apellido Paterno", Required ="Required"})
                                @Html.ValidationMessageFor(model => model.ApellidoPaterno,"", new {@class = "text-danger"})
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <label>Apellido Materno:</label>
                                @Html.TextBoxFor(model => model.ApellidoMaterno, null , new {@class = "form-control", placeHolder = "Apellido Materno"})
                                @Html.ValidationMessageFor(model => model.ApellidoMaterno, "", new {@class = "text-danger"})
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
                                <label>Edad:</label>
                                @Html.TextBoxFor(model => model.Edad, null, new {@class = "form-control", placeHolder = "0"})
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                                <label>Calle:</label>
                                @Html.TextBoxFor(model => model.DireccionVM.Calle, null, new {@class = "form-control", placeHolder = "Calle"})
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <label>Colonia</label>
                                @Html.TextBoxFor(model => model.DireccionVM.Colonia,null, new {@class = "form-control", placeHolder = "Colonia"})
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
                                <label>Codigo Postal</label>
                                @Html.TextBoxFor(model => model.DireccionVM.Colonia, null, new {@class = "form-control", placeHolder = "C.p"})
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <label>Num.Interior:</label>
                                @Html.TextBoxFor(model => model.DireccionVM.NumeroInterior, null , new {@class = "form-control", placeHolder ="Num.Interior"})
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
                                <label>Num.Exterior:</label>
                                @Html.TextBoxFor(model => model.DireccionVM.NumeroExterior, null, new { @class = "form-control", placeHolder = "Num.Exterior" })
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <label>Num.Celular:</label>
                                @Html.TextBoxFor(model => model.TelefonoVM.NumeroCelular, null, new {@class = "form-control", placeHolder = "Num.Celular"})
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <label>Num.Local:</label>
                                @Html.TextBoxFor(model => model.TelefonoVM.NumeroFijo, null, new { @class = "form-control", placeHolder = "Num.Fijo" })
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                                <label>Accion:</label>
                                <input type="submit" value="Guardar" class="btn btn-sm btn-block btn-success"/>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>